name: Pull Request Validation

on:
  pull_request:
    branches: [ master, main ]

jobs:
  # Quick validation for PRs
  validate:
    runs-on: ubuntu-latest
    name: Validate Pull Request
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Restore .NET dependencies
      run: dotnet restore Calculator.sln
      
    - name: Build .NET solution
      run: dotnet build Calculator.sln --no-restore
      
    - name: Run .NET tests
      run: dotnet test Calculator.Tests/Calculator.Tests.csproj --no-build --verbosity normal
      
    - name: Install Angular dependencies
      run: |
        cd Calculator.Web
        npm ci
        
    - name: Build Angular app
      run: |
        cd Calculator.Web
        npm run build
        
    - name: Lint check (if available)
      run: |
        echo "✅ Code validation completed"
        
  # Docker build test
  docker-build-test:
    runs-on: ubuntu-latest
    name: Test Docker Build
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test build Calculator Server
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Calculator.Server/Dockerfile
        push: false
        tags: test/calculator-server:latest
        
    - name: Test build Calculator Web
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Calculator.Web/Dockerfile
        push: false
        tags: test/calculator-web:latest